[package]
name = "tirc"
version = "0.1.0"
edition = "2021"

[dependencies]
failure = "0.1.8"
futures = "0.3.28"
irc = { git = "https://github.com/aatxe/irc.git", branch = "develop" }
tokio = { version = "1.28.2", features = ["full"] }
crossterm = { version = "0.26.1", features = ["serde"] }
tui = { version="0.21.0", package = "ratatui" }
tui-input = { version = "*", features = ["crossterm"] }
anyhow = "1.0.71"
