[package]
name = "tirc-backend-matrix"
version.workspace = true
edition.workspace = true

[dependencies]
tirc-core = { path = "../tirc-core" }
anyhow = { workspace = true }
async-trait = { workspace = true }
chrono = { workspace = true }
futures = { workspace = true }
log = { workspace = true }
matrix-sdk = { workspace = true }
matrix-sdk-ui = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
tokio = { workspace = true }
xdg = { workspace = true }
