[package]
name = "tirc-lua"
version.workspace = true
edition.workspace = true

[dependencies]
tirc-core = { path = "../tirc-core" }
anyhow = { workspace = true }
chrono = { workspace = true }
log = { workspace = true }
mlua = { workspace = true }
ratatui = { workspace = true }
reqwest = { workspace = true }
semver = { workspace = true }
serde_json = { workspace = true }
tokio = { workspace = true }
twox-hash = { workspace = true }
